MONGO_URI : mongodb+srv://nghia:RSopELht6beTlZ2x@ai-contest.igk5z.mongodb.net/test
MONGO_DB : ai_contest

PYTHON3_VENV : "/media/nghialuffy/VMWAVE/BKDN_AI_CONTEST/tool_run_model/python3_venv/bin/python3"
